/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pairingmessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pairing/pairingmessage.pb-c.h"
void   pairing__pairing_request__init
                     (Pairing__PairingRequest         *message)
{
  static const Pairing__PairingRequest init_value = PAIRING__PAIRING_REQUEST__INIT;
  *message = init_value;
}
size_t pairing__pairing_request__get_packed_size
                     (const Pairing__PairingRequest *message)
{
  assert(message->base.descriptor == &pairing__pairing_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pairing__pairing_request__pack
                     (const Pairing__PairingRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pairing__pairing_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pairing__pairing_request__pack_to_buffer
                     (const Pairing__PairingRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pairing__pairing_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pairing__PairingRequest *
       pairing__pairing_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pairing__PairingRequest *)
     protobuf_c_message_unpack (&pairing__pairing_request__descriptor,
                                allocator, len, data);
}
void   pairing__pairing_request__free_unpacked
                     (Pairing__PairingRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pairing__pairing_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pairing__pairing_request_ack__init
                     (Pairing__PairingRequestAck         *message)
{
  static const Pairing__PairingRequestAck init_value = PAIRING__PAIRING_REQUEST_ACK__INIT;
  *message = init_value;
}
size_t pairing__pairing_request_ack__get_packed_size
                     (const Pairing__PairingRequestAck *message)
{
  assert(message->base.descriptor == &pairing__pairing_request_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pairing__pairing_request_ack__pack
                     (const Pairing__PairingRequestAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pairing__pairing_request_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pairing__pairing_request_ack__pack_to_buffer
                     (const Pairing__PairingRequestAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pairing__pairing_request_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pairing__PairingRequestAck *
       pairing__pairing_request_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pairing__PairingRequestAck *)
     protobuf_c_message_unpack (&pairing__pairing_request_ack__descriptor,
                                allocator, len, data);
}
void   pairing__pairing_request_ack__free_unpacked
                     (Pairing__PairingRequestAck *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pairing__pairing_request_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pairing__pairing_encoding__init
                     (Pairing__PairingEncoding         *message)
{
  static const Pairing__PairingEncoding init_value = PAIRING__PAIRING_ENCODING__INIT;
  *message = init_value;
}
size_t pairing__pairing_encoding__get_packed_size
                     (const Pairing__PairingEncoding *message)
{
  assert(message->base.descriptor == &pairing__pairing_encoding__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pairing__pairing_encoding__pack
                     (const Pairing__PairingEncoding *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pairing__pairing_encoding__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pairing__pairing_encoding__pack_to_buffer
                     (const Pairing__PairingEncoding *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pairing__pairing_encoding__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pairing__PairingEncoding *
       pairing__pairing_encoding__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pairing__PairingEncoding *)
     protobuf_c_message_unpack (&pairing__pairing_encoding__descriptor,
                                allocator, len, data);
}
void   pairing__pairing_encoding__free_unpacked
                     (Pairing__PairingEncoding *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pairing__pairing_encoding__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pairing__pairing_option__init
                     (Pairing__PairingOption         *message)
{
  static const Pairing__PairingOption init_value = PAIRING__PAIRING_OPTION__INIT;
  *message = init_value;
}
size_t pairing__pairing_option__get_packed_size
                     (const Pairing__PairingOption *message)
{
  assert(message->base.descriptor == &pairing__pairing_option__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pairing__pairing_option__pack
                     (const Pairing__PairingOption *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pairing__pairing_option__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pairing__pairing_option__pack_to_buffer
                     (const Pairing__PairingOption *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pairing__pairing_option__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pairing__PairingOption *
       pairing__pairing_option__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pairing__PairingOption *)
     protobuf_c_message_unpack (&pairing__pairing_option__descriptor,
                                allocator, len, data);
}
void   pairing__pairing_option__free_unpacked
                     (Pairing__PairingOption *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pairing__pairing_option__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pairing__pairing_configuration__init
                     (Pairing__PairingConfiguration         *message)
{
  static const Pairing__PairingConfiguration init_value = PAIRING__PAIRING_CONFIGURATION__INIT;
  *message = init_value;
}
size_t pairing__pairing_configuration__get_packed_size
                     (const Pairing__PairingConfiguration *message)
{
  assert(message->base.descriptor == &pairing__pairing_configuration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pairing__pairing_configuration__pack
                     (const Pairing__PairingConfiguration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pairing__pairing_configuration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pairing__pairing_configuration__pack_to_buffer
                     (const Pairing__PairingConfiguration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pairing__pairing_configuration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pairing__PairingConfiguration *
       pairing__pairing_configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pairing__PairingConfiguration *)
     protobuf_c_message_unpack (&pairing__pairing_configuration__descriptor,
                                allocator, len, data);
}
void   pairing__pairing_configuration__free_unpacked
                     (Pairing__PairingConfiguration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pairing__pairing_configuration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pairing__pairing_configuration_ack__init
                     (Pairing__PairingConfigurationAck         *message)
{
  static const Pairing__PairingConfigurationAck init_value = PAIRING__PAIRING_CONFIGURATION_ACK__INIT;
  *message = init_value;
}
size_t pairing__pairing_configuration_ack__get_packed_size
                     (const Pairing__PairingConfigurationAck *message)
{
  assert(message->base.descriptor == &pairing__pairing_configuration_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pairing__pairing_configuration_ack__pack
                     (const Pairing__PairingConfigurationAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pairing__pairing_configuration_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pairing__pairing_configuration_ack__pack_to_buffer
                     (const Pairing__PairingConfigurationAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pairing__pairing_configuration_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pairing__PairingConfigurationAck *
       pairing__pairing_configuration_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pairing__PairingConfigurationAck *)
     protobuf_c_message_unpack (&pairing__pairing_configuration_ack__descriptor,
                                allocator, len, data);
}
void   pairing__pairing_configuration_ack__free_unpacked
                     (Pairing__PairingConfigurationAck *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pairing__pairing_configuration_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pairing__pairing_secret__init
                     (Pairing__PairingSecret         *message)
{
  static const Pairing__PairingSecret init_value = PAIRING__PAIRING_SECRET__INIT;
  *message = init_value;
}
size_t pairing__pairing_secret__get_packed_size
                     (const Pairing__PairingSecret *message)
{
  assert(message->base.descriptor == &pairing__pairing_secret__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pairing__pairing_secret__pack
                     (const Pairing__PairingSecret *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pairing__pairing_secret__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pairing__pairing_secret__pack_to_buffer
                     (const Pairing__PairingSecret *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pairing__pairing_secret__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pairing__PairingSecret *
       pairing__pairing_secret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pairing__PairingSecret *)
     protobuf_c_message_unpack (&pairing__pairing_secret__descriptor,
                                allocator, len, data);
}
void   pairing__pairing_secret__free_unpacked
                     (Pairing__PairingSecret *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pairing__pairing_secret__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pairing__pairing_secret_ack__init
                     (Pairing__PairingSecretAck         *message)
{
  static const Pairing__PairingSecretAck init_value = PAIRING__PAIRING_SECRET_ACK__INIT;
  *message = init_value;
}
size_t pairing__pairing_secret_ack__get_packed_size
                     (const Pairing__PairingSecretAck *message)
{
  assert(message->base.descriptor == &pairing__pairing_secret_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pairing__pairing_secret_ack__pack
                     (const Pairing__PairingSecretAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pairing__pairing_secret_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pairing__pairing_secret_ack__pack_to_buffer
                     (const Pairing__PairingSecretAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pairing__pairing_secret_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pairing__PairingSecretAck *
       pairing__pairing_secret_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pairing__PairingSecretAck *)
     protobuf_c_message_unpack (&pairing__pairing_secret_ack__descriptor,
                                allocator, len, data);
}
void   pairing__pairing_secret_ack__free_unpacked
                     (Pairing__PairingSecretAck *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pairing__pairing_secret_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pairing__pairing_message__init
                     (Pairing__PairingMessage         *message)
{
  static const Pairing__PairingMessage init_value = PAIRING__PAIRING_MESSAGE__INIT;
  *message = init_value;
}
size_t pairing__pairing_message__get_packed_size
                     (const Pairing__PairingMessage *message)
{
  assert(message->base.descriptor == &pairing__pairing_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pairing__pairing_message__pack
                     (const Pairing__PairingMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pairing__pairing_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pairing__pairing_message__pack_to_buffer
                     (const Pairing__PairingMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pairing__pairing_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pairing__PairingMessage *
       pairing__pairing_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pairing__PairingMessage *)
     protobuf_c_message_unpack (&pairing__pairing_message__descriptor,
                                allocator, len, data);
}
void   pairing__pairing_message__free_unpacked
                     (Pairing__PairingMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pairing__pairing_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pairing__pairing_request__field_descriptors[2] =
{
  {
    "service_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingRequest, service_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingRequest, client_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pairing__pairing_request__field_indices_by_name[] = {
  1,   /* field[1] = client_name */
  0,   /* field[0] = service_name */
};
static const ProtobufCIntRange pairing__pairing_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pairing__pairing_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pairing.PairingRequest",
  "PairingRequest",
  "Pairing__PairingRequest",
  "pairing",
  sizeof(Pairing__PairingRequest),
  2,
  pairing__pairing_request__field_descriptors,
  pairing__pairing_request__field_indices_by_name,
  1,  pairing__pairing_request__number_ranges,
  (ProtobufCMessageInit) pairing__pairing_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pairing__pairing_request_ack__field_descriptors[1] =
{
  {
    "server_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingRequestAck, server_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pairing__pairing_request_ack__field_indices_by_name[] = {
  0,   /* field[0] = server_name */
};
static const ProtobufCIntRange pairing__pairing_request_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor pairing__pairing_request_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pairing.PairingRequestAck",
  "PairingRequestAck",
  "Pairing__PairingRequestAck",
  "pairing",
  sizeof(Pairing__PairingRequestAck),
  1,
  pairing__pairing_request_ack__field_descriptors,
  pairing__pairing_request_ack__field_indices_by_name,
  1,  pairing__pairing_request_ack__number_ranges,
  (ProtobufCMessageInit) pairing__pairing_request_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue pairing__pairing_encoding__encoding_type__enum_values_by_number[6] =
{
  { "UNRECOGNIZED", "PAIRING__PAIRING_ENCODING__ENCODING_TYPE__UNRECOGNIZED", -1 },
  { "ENCODING_TYPE_UNKNOWN", "PAIRING__PAIRING_ENCODING__ENCODING_TYPE__ENCODING_TYPE_UNKNOWN", 0 },
  { "ENCODING_TYPE_ALPHANUMERIC", "PAIRING__PAIRING_ENCODING__ENCODING_TYPE__ENCODING_TYPE_ALPHANUMERIC", 1 },
  { "ENCODING_TYPE_NUMERIC", "PAIRING__PAIRING_ENCODING__ENCODING_TYPE__ENCODING_TYPE_NUMERIC", 2 },
  { "ENCODING_TYPE_HEXADECIMAL", "PAIRING__PAIRING_ENCODING__ENCODING_TYPE__ENCODING_TYPE_HEXADECIMAL", 3 },
  { "ENCODING_TYPE_QRCODE", "PAIRING__PAIRING_ENCODING__ENCODING_TYPE__ENCODING_TYPE_QRCODE", 4 },
};
static const ProtobufCIntRange pairing__pairing_encoding__encoding_type__value_ranges[] = {
{-1, 0},{0, 6}
};
static const ProtobufCEnumValueIndex pairing__pairing_encoding__encoding_type__enum_values_by_name[6] =
{
  { "ENCODING_TYPE_ALPHANUMERIC", 2 },
  { "ENCODING_TYPE_HEXADECIMAL", 4 },
  { "ENCODING_TYPE_NUMERIC", 3 },
  { "ENCODING_TYPE_QRCODE", 5 },
  { "ENCODING_TYPE_UNKNOWN", 1 },
  { "UNRECOGNIZED", 0 },
};
const ProtobufCEnumDescriptor pairing__pairing_encoding__encoding_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "pairing.PairingEncoding.EncodingType",
  "EncodingType",
  "Pairing__PairingEncoding__EncodingType",
  "pairing",
  6,
  pairing__pairing_encoding__encoding_type__enum_values_by_number,
  6,
  pairing__pairing_encoding__encoding_type__enum_values_by_name,
  1,
  pairing__pairing_encoding__encoding_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor pairing__pairing_encoding__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingEncoding, type),
    &pairing__pairing_encoding__encoding_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symbol_length",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingEncoding, symbol_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pairing__pairing_encoding__field_indices_by_name[] = {
  1,   /* field[1] = symbol_length */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange pairing__pairing_encoding__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pairing__pairing_encoding__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pairing.PairingEncoding",
  "PairingEncoding",
  "Pairing__PairingEncoding",
  "pairing",
  sizeof(Pairing__PairingEncoding),
  2,
  pairing__pairing_encoding__field_descriptors,
  pairing__pairing_encoding__field_indices_by_name,
  1,  pairing__pairing_encoding__number_ranges,
  (ProtobufCMessageInit) pairing__pairing_encoding__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pairing__pairing_option__field_descriptors[3] =
{
  {
    "input_encodings",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Pairing__PairingOption, n_input_encodings),
    offsetof(Pairing__PairingOption, input_encodings),
    &pairing__pairing_encoding__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output_encodings",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Pairing__PairingOption, n_output_encodings),
    offsetof(Pairing__PairingOption, output_encodings),
    &pairing__pairing_encoding__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "preferred_role",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingOption, preferred_role),
    &pairing__role_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pairing__pairing_option__field_indices_by_name[] = {
  0,   /* field[0] = input_encodings */
  1,   /* field[1] = output_encodings */
  2,   /* field[2] = preferred_role */
};
static const ProtobufCIntRange pairing__pairing_option__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pairing__pairing_option__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pairing.PairingOption",
  "PairingOption",
  "Pairing__PairingOption",
  "pairing",
  sizeof(Pairing__PairingOption),
  3,
  pairing__pairing_option__field_descriptors,
  pairing__pairing_option__field_indices_by_name,
  1,  pairing__pairing_option__number_ranges,
  (ProtobufCMessageInit) pairing__pairing_option__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pairing__pairing_configuration__field_descriptors[2] =
{
  {
    "encoding",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingConfiguration, encoding),
    &pairing__pairing_encoding__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_role",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingConfiguration, client_role),
    &pairing__role_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pairing__pairing_configuration__field_indices_by_name[] = {
  1,   /* field[1] = client_role */
  0,   /* field[0] = encoding */
};
static const ProtobufCIntRange pairing__pairing_configuration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pairing__pairing_configuration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pairing.PairingConfiguration",
  "PairingConfiguration",
  "Pairing__PairingConfiguration",
  "pairing",
  sizeof(Pairing__PairingConfiguration),
  2,
  pairing__pairing_configuration__field_descriptors,
  pairing__pairing_configuration__field_indices_by_name,
  1,  pairing__pairing_configuration__number_ranges,
  (ProtobufCMessageInit) pairing__pairing_configuration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define pairing__pairing_configuration_ack__field_descriptors NULL
#define pairing__pairing_configuration_ack__field_indices_by_name NULL
#define pairing__pairing_configuration_ack__number_ranges NULL
const ProtobufCMessageDescriptor pairing__pairing_configuration_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pairing.PairingConfigurationAck",
  "PairingConfigurationAck",
  "Pairing__PairingConfigurationAck",
  "pairing",
  sizeof(Pairing__PairingConfigurationAck),
  0,
  pairing__pairing_configuration_ack__field_descriptors,
  pairing__pairing_configuration_ack__field_indices_by_name,
  0,  pairing__pairing_configuration_ack__number_ranges,
  (ProtobufCMessageInit) pairing__pairing_configuration_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pairing__pairing_secret__field_descriptors[1] =
{
  {
    "secret",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingSecret, secret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pairing__pairing_secret__field_indices_by_name[] = {
  0,   /* field[0] = secret */
};
static const ProtobufCIntRange pairing__pairing_secret__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor pairing__pairing_secret__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pairing.PairingSecret",
  "PairingSecret",
  "Pairing__PairingSecret",
  "pairing",
  sizeof(Pairing__PairingSecret),
  1,
  pairing__pairing_secret__field_descriptors,
  pairing__pairing_secret__field_indices_by_name,
  1,  pairing__pairing_secret__number_ranges,
  (ProtobufCMessageInit) pairing__pairing_secret__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pairing__pairing_secret_ack__field_descriptors[1] =
{
  {
    "secret",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingSecretAck, secret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pairing__pairing_secret_ack__field_indices_by_name[] = {
  0,   /* field[0] = secret */
};
static const ProtobufCIntRange pairing__pairing_secret_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor pairing__pairing_secret_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pairing.PairingSecretAck",
  "PairingSecretAck",
  "Pairing__PairingSecretAck",
  "pairing",
  sizeof(Pairing__PairingSecretAck),
  1,
  pairing__pairing_secret_ack__field_descriptors,
  pairing__pairing_secret_ack__field_indices_by_name,
  1,  pairing__pairing_secret_ack__number_ranges,
  (ProtobufCMessageInit) pairing__pairing_secret_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue pairing__pairing_message__status__enum_values_by_number[6] =
{
  { "UNRECOGNIZED", "PAIRING__PAIRING_MESSAGE__STATUS__UNRECOGNIZED", -1 },
  { "UNKNOWN", "PAIRING__PAIRING_MESSAGE__STATUS__UNKNOWN", 0 },
  { "STATUS_OK", "PAIRING__PAIRING_MESSAGE__STATUS__STATUS_OK", 200 },
  { "STATUS_ERROR", "PAIRING__PAIRING_MESSAGE__STATUS__STATUS_ERROR", 400 },
  { "STATUS_BAD_CONFIGURATION", "PAIRING__PAIRING_MESSAGE__STATUS__STATUS_BAD_CONFIGURATION", 401 },
  { "STATUS_BAD_SECRET", "PAIRING__PAIRING_MESSAGE__STATUS__STATUS_BAD_SECRET", 402 },
};
static const ProtobufCIntRange pairing__pairing_message__status__value_ranges[] = {
{-1, 0},{200, 2},{400, 3},{0, 6}
};
static const ProtobufCEnumValueIndex pairing__pairing_message__status__enum_values_by_name[6] =
{
  { "STATUS_BAD_CONFIGURATION", 4 },
  { "STATUS_BAD_SECRET", 5 },
  { "STATUS_ERROR", 3 },
  { "STATUS_OK", 2 },
  { "UNKNOWN", 1 },
  { "UNRECOGNIZED", 0 },
};
const ProtobufCEnumDescriptor pairing__pairing_message__status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "pairing.PairingMessage.Status",
  "Status",
  "Pairing__PairingMessage__Status",
  "pairing",
  6,
  pairing__pairing_message__status__enum_values_by_number,
  6,
  pairing__pairing_message__status__enum_values_by_name,
  3,
  pairing__pairing_message__status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor pairing__pairing_message__field_descriptors[10] =
{
  {
    "protocol_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingMessage, protocol_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingMessage, status),
    &pairing__pairing_message__status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_case",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingMessage, request_case),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pairing_request",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingMessage, pairing_request),
    &pairing__pairing_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pairing_request_ack",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingMessage, pairing_request_ack),
    &pairing__pairing_request_ack__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pairing_option",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingMessage, pairing_option),
    &pairing__pairing_option__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pairing_configuration",
    30,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingMessage, pairing_configuration),
    &pairing__pairing_configuration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pairing_configuration_ack",
    31,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingMessage, pairing_configuration_ack),
    &pairing__pairing_configuration_ack__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pairing_secret",
    40,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingMessage, pairing_secret),
    &pairing__pairing_secret__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pairing_secret_ack",
    41,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pairing__PairingMessage, pairing_secret_ack),
    &pairing__pairing_secret_ack__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pairing__pairing_message__field_indices_by_name[] = {
  6,   /* field[6] = pairing_configuration */
  7,   /* field[7] = pairing_configuration_ack */
  5,   /* field[5] = pairing_option */
  3,   /* field[3] = pairing_request */
  4,   /* field[4] = pairing_request_ack */
  8,   /* field[8] = pairing_secret */
  9,   /* field[9] = pairing_secret_ack */
  0,   /* field[0] = protocol_version */
  2,   /* field[2] = request_case */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange pairing__pairing_message__number_ranges[5 + 1] =
{
  { 1, 0 },
  { 10, 3 },
  { 20, 5 },
  { 30, 6 },
  { 40, 8 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor pairing__pairing_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pairing.PairingMessage",
  "PairingMessage",
  "Pairing__PairingMessage",
  "pairing",
  sizeof(Pairing__PairingMessage),
  10,
  pairing__pairing_message__field_descriptors,
  pairing__pairing_message__field_indices_by_name,
  5,  pairing__pairing_message__number_ranges,
  (ProtobufCMessageInit) pairing__pairing_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue pairing__role_type__enum_values_by_number[4] =
{
  { "UNRECOGNIZED", "PAIRING__ROLE_TYPE__UNRECOGNIZED", -1 },
  { "ROLE_TYPE_UNKNOWN", "PAIRING__ROLE_TYPE__ROLE_TYPE_UNKNOWN", 0 },
  { "ROLE_TYPE_INPUT", "PAIRING__ROLE_TYPE__ROLE_TYPE_INPUT", 1 },
  { "ROLE_TYPE_OUTPUT", "PAIRING__ROLE_TYPE__ROLE_TYPE_OUTPUT", 2 },
};
static const ProtobufCIntRange pairing__role_type__value_ranges[] = {
{-1, 0},{0, 4}
};
static const ProtobufCEnumValueIndex pairing__role_type__enum_values_by_name[4] =
{
  { "ROLE_TYPE_INPUT", 2 },
  { "ROLE_TYPE_OUTPUT", 3 },
  { "ROLE_TYPE_UNKNOWN", 1 },
  { "UNRECOGNIZED", 0 },
};
const ProtobufCEnumDescriptor pairing__role_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "pairing.RoleType",
  "RoleType",
  "Pairing__RoleType",
  "pairing",
  4,
  pairing__role_type__enum_values_by_number,
  4,
  pairing__role_type__enum_values_by_name,
  1,
  pairing__role_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
